# Generated by Django 5.2 on 2025-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_source', models.CharField(choices=[('fatsecret', 'FATSECRET'), ('other', 'OTHER')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('foursquare_chain_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
